"""Curated JSON request/response schemas for OnPing driver `/location/add` endpoints.

This module is the single source of truth for the on-disk skill tree.
Each entry in `SCHEMAS` describes one driver's `/location/add` (or `/bridge/add`
in the Sparkplug case) POST endpoint:

  - `endpoint`        — HTTP method + path
  - `handler`         — `file:line` of the handler function in onping (traceability)
  - `request_type`    — Haskell type name parsed from the request body
  - `request_schema`  — hand-curated JSON shape (field name -> type description)
  - `response_type`   — Haskell return type
  - `response_schema` — hand-curated JSON shape of the success body

Schemas are HAND-CURATED from reading the Haskell handler + record types in
`onping/Handler/<Driver>/Service.hs` and the
`onping-handler-types` (or `OnPing.Frontend.Types.*`) packages. When Haskell
types drift, re-verify against the recorded `handler` location and update the
matching entry here. All per-driver `show_add_schema.py` scripts read from
this dict; nothing else should redefine these schemas inline.

Type-description vocabulary used in `request_schema` / `response_schema`:
  - `"string"`, `"int"`, `"float"`, `"bool"`     — primitive JSON types
  - `"X | null"`                                 — nullable
  - `["X"]`                                      — JSON array of X
  - `{...}`                                      — nested object
  - `"<TypeName>"`                               — opaque OnPing type (see source)

Two response patterns appear:
  - Group A (classic, `parseInsecureJsonBody` -> `Handler Value`)
      success body: `{"refId": int, "mongoKey": string}`
  - Group B (newer, `requireInsecureJsonBody` -> `Handler (OnpingResponse T)`)
      success body: the JSON of T directly (no wrapper)
      error body:   `{"error": "<message>"}`
"""

from __future__ import annotations

SCHEMAS: dict[str, dict] = {
    # ───────────────────────── Group A (classic) ─────────────────────────
    "bristol": {
        "driver": "bristol",
        "endpoint": "POST /bristol/location/add",
        "handler": "onping/Handler/Bristol/Service.hs",
        "request_type": "BristolLocationConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/Bristol.hs",
        "request_schema": {
            "id": "LocationId | null",
            "refId": "LocationIdRef | null",
            "name": "string",
            "lumberjackUrl": "string",
            "lumberjackPort": "int",
            "pollTime": "int",
            "retryLimit": "int",
            "usbSpeed": "USBSpeed",
            "username": "string",
            "password": "string",
            "siteId": "SiteIdRef | null",
            "companyId": "CompanyIdRef | null",
            "groupId": "GroupId | null",
            "gps": "GPSStorable | null",
        },
        "response_type": "Value",
        "response_schema": {"refId": "int", "mongoKey": "string"},
    },
    "roc-tlp": {
        "driver": "roc-tlp",
        "endpoint": "POST /roc/tlp/location/add",
        "handler": "onping/Handler/RocTlp/Service.hs",
        "request_type": "RocTlpLocationConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/RocTlp.hs",
        "request_schema": {
            "id": "LocationId | null",
            "refId": "LocationIdRef | null",
            "name": "string",
            "plcUrl": "string",
            "plcPort": "int",
            "lumberjackUrl": "string",
            "lumberjackPort": "int",
            "pollTime": "int",
            "retryLimit": "int",
            "deviceUserName": "string",
            "devicePassword": "int",
            "deviceType": "DeviceType",
            "unitAddress": "int",
            "groupAddress": "int",
            "timeUpdate": "TimeUpdate | null",
            "siteId": "SiteIdRef | null",
            "companyId": "CompanyIdRef | null",
            "groupId": "GroupId | null",
            "coordinates": "GPSStorable | null",
        },
        "response_type": "Value",
        "response_schema": {"refId": "int", "mongoKey": "string"},
    },
    "modbus-flexible": {
        "driver": "modbus-flexible",
        "endpoint": "POST /modbus/flexible/location/add",
        "handler": "onping/Handler/ModbusFlexible/Service.hs",
        "request_type": "ModbusFlexibleLocationConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/ModbusFlexible.hs",
        "request_schema": {
            "id": "LocationId | null",
            "refId": "LocationIdRef | null",
            "name": "string",
            "plcUrl": "string",
            "plcPort": "int",
            "lumberjackUrl": "string",
            "lumberjackPort": "int",
            "pollTime": "int",
            "retryLimit": "int",
            "knownController": "KnownController | null",
            "idType": "IdType",
            "unitId": "int",
            "devicePath": "string | null",
            "commSpeed": "USBSpeed | null",
            "bitsPerWord": "int | null",
            "stopBits": "USBStopBits | null",
            "parity": "USBParity | null",
            "flowControl": "USBFlowControl | null",
            "timeout": "int | null",
            "byteSwap": "ModbusByteSwap",
            "endianness": "ModbusEndianness",
            "networkTimeout": "int",
            "siteId": "SiteIdRef | null",
            "companyId": "CompanyIdRef | null",
            "groupId": "GroupId | null",
            "gps": "GPSStorable | null",
            "delta": "float | null",
        },
        "response_type": "Value",
        "response_schema": {"refId": "int", "mongoKey": "string"},
    },
    "control-logix": {
        "driver": "control-logix",
        "endpoint": "POST /control/logix/location/add",
        "handler": "onping/Handler/ControlLogix/Service.hs",
        "request_type": "ControlLogixConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/ControlLogix.hs",
        "request_schema": {
            "id": "LocationId | null",
            "refId": "LocationIdRef | null",
            "name": "string",
            "plcUrl": "string",
            "plcPort": "int",
            "lumberjackUrl": "string",
            "lumberjackPort": "int",
            "pollTime": "int",
            "siteId": "SiteIdRef | null",
            "companyId": "CompanyIdRef | null",
            "groupId": "GroupId | null",
            "coordinates": "GPSStorable | null",
        },
        "response_type": "Value",
        "response_schema": {"refId": "int", "mongoKey": "string"},
    },
    "total-flow": {
        "driver": "total-flow",
        "endpoint": "POST /total/flow/location/add",
        "handler": "onping/Handler/TotalFlow/Service.hs",
        "request_type": "TotalFlowLocationConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/TotalFlow.hs",
        "request_schema": {
            "id": "LocationId | null",
            "refId": "LocationIdRef | null",
            "name": "string",
            "network": "TotalFlowNetwork",
            "lumberjackUrl": "string",
            "lumberjackPort": "int",
            "pollTime": "int",
            "deviceId": "string",
            "retryLimit": "int",
            "siteId": "SiteIdRef | null",
            "companyId": "CompanyIdRef | null",
            "groupId": "GroupId | null",
            "coordinates": "GPSStorable | null",
            "password": "int | null",
            "responseTimeout": "DeviceResponseTimeout",
        },
        "response_type": "Value",
        "response_schema": {"refId": "int", "mongoKey": "string"},
    },
    "micrologix": {
        "driver": "micrologix",
        "endpoint": "POST /micrologix/location/add",
        "handler": "onping/Handler/Micrologix/Service.hs",
        "request_type": "MicrologixLocationConfig",
        "request_type_source": "onping-types/onping-handler-types/src/Onping/Types/Handler/Micrologix.hs",
        "notes": "Same handler supports add+update: locationId=null adds, locationId=set updates.",
        "request_schema": {
            "companyId": "CompanyIdRef",
            "siteId": "SiteIdRef",
            "locationId": "LocationId | null",
            "locationRefId": "LocationIdRef | null",
            "name": "string",
            "url": "string",
            "port": "int",
            "locationAddress": "MicrologixAddress",
            "pollTime": "int",
            "lastPollTime": "int",
            "delete": "int",
            "registerMap": [["int", "MicrologixDataId"]],
            "descriptionMap": [["MicrologixDataId", "string"]],
            "dataInfoMap": [["int", "MicrologixDataInfo"]],
            "totalRetryCount": "int",
            "retryCount": "RetryType",
            "data": "MicrologixDataEntity",
            "groupId": "GroupId | null",
            "coordinates": "GPSStorable | null",
            "timeout": "int",
        },
        "response_type": "Value",
        "response_schema": {"MicrologixLocationId": "int"},
    },
    # ───────────────────────── Group B (newer) ─────────────────────────
    "singlewell-manual": {
        "driver": "singlewell-manual",
        "endpoint": "POST /singlewellmanual/location/add",
        "handler": "onping/Handler/SingleWellManual/Service.hs",
        "request_type": "ManualLocationConfigTagged",
        "request_type_source": "onping/Handler/SingleWellManual/Service.hs",
        "request_schema": {
            "name": "string",
            "id": "int | null",
            "url": "string",
            "port": "int",
            "group_id": "int",
            "location_ref_id": "int | null",
            "company_id": "int",
            "site_id": "int",
            "notes": "string | null",
            "data": "[ManualTag] | null",
            "coordinates": "GPS | null",
        },
        "response_type": "OnpingResponse ManualLocationKey",
        "response_schema": {"_success": "ManualLocationKey (mongo ObjectId string)"},
    },
    "mqtt-json": {
        "driver": "mqtt-json",
        "endpoint": "POST /mqtt/json/location/add",
        "handler": "onping/Handler/MQTT/JSON/Service.hs",
        "request_type": "MqttLocationInfoConfig",
        "request_type_source": "OnPing.Frontend.Types.MqttJson",
        "request_schema": {
            "mqtt_loc_info": {
                "loc_info_name": "string",
                "loc_info_loc_id": "int | null",
                "loc_info_site_id": "int",
                "loc_info_company_id": "int",
            },
            "mqtt_loc_gps": "GPS | null",
            "mqtt_loc_group": "int",
            "mqtt_loc_mongo_id": "ObjectId | null",
            "mqtt_loc_url": "string",
            "mqtt_loc_port": "int",
        },
        "response_type": "OnpingResponse MqttLocationInfoConfig",
        "response_schema": {
            "mqtt_loc_info": "object",
            "mqtt_loc_gps": "GPS | null",
            "mqtt_loc_group": "int",
            "mqtt_loc_mongo_id": "ObjectId",
            "mqtt_loc_url": "string",
            "mqtt_loc_port": "int",
        },
    },
    "opc-ua": {
        "driver": "opc-ua",
        "endpoint": "POST /opc/ua/location/add",
        "handler": "onping/Handler/OPC/UA/Service.hs",
        "request_type": "OpcUaLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.OpcUa",
        "request_schema": {
            "opc_ua_loc_config_loc_id": "ObjectId | null",
            "opc_ua_loc_config_ref_id": "int | null",
            "opc_ua_loc_config_company_id": "int",
            "opc_ua_loc_config_site_id": "int",
            "opc_ua_loc_config_group_id": "int",
            "opc_ua_loc_config_loc_name": "string",
            "opc_ua_loc_config_url": "string",
            "opc_ua_loc_config_port": "int",
            "opc_ua_loc_config_endpoint": "string",
            "opc_ua_loc_config_username": "string | null",
            "opc_ua_loc_config_password": "string | null",
            "opc_ua_loc_config_security_policy": "string",
            "opc_ua_loc_config_certificate": "string | null",
            "opc_ua_loc_config_poll_frequency": "int",
            "opc_ua_loc_config_last_poll_time": "PlowUTCTime",
            "opc_ua_loc_config_retries": "int",
            "opc_ua_loc_config_local_only": "bool",
            "opc_ua_loc_config_gps": "GPS | null",
        },
        "response_type": "OnpingResponse OpcUaLocationConfig",
        "response_schema": "<echoes the request shape with populated loc_id and ref_id>",
    },
    "wellpilot": {
        "driver": "wellpilot",
        "endpoint": "POST /wellpilot/location/add",
        "handler": "onping/Handler/WellPilot/Service.hs",
        "request_type": "WellPilotLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.WellPilot",
        "request_schema": {
            "well_pilot_config_loc_id": "ObjectId | null",
            "well_pilot_config_ref_id": "int | null",
            "well_pilot_config_site_id": "int",
            "well_pilot_config_company_id": "int",
            "well_pilot_config_group_id": "int",
            "well_pilot_config_loc_name": "string",
            "well_pilot_config_url": "string",
            "well_pilot_config_port": "int",
            "well_pilot_config_device_id": "int",
            "well_pilot_config_serial_port": "string",
            "well_pilot_config_comm_speed": "int",
            "well_pilot_config_timeout": "int",
            "well_pilot_config_timezone": "string",
            "well_pilot_config_gps": "GPS | null",
            "well_pilot_config_last_poll_time": "PlowUTCTime",
            "well_pilot_config_poll_frequency": "int",
            "well_pilot_config_retries": "int",
            "well_pilot_config_retry_delay": "int",
        },
        "response_type": "OnpingResponse ()",
        "response_schema": {},
    },
    "unico": {
        "driver": "unico",
        "endpoint": "POST /unico/location/add",
        "handler": "onping/Handler/Unico/Service.hs",
        "request_type": "UnicoLocationConfig",
        "request_type_source": "Unico.Modbus.Types",
        "request_schema": {
            "unico_config_loc_id": "ObjectId | null",
            "unico_config_ref_id": "int | null",
            "unico_config_site_id": "int",
            "unico_config_company_id": "int",
            "unico_config_url": "string",
            "unico_config_port": "int",
            "unico_config_group_id": "int",
            "unico_config_loc_name": "string",
            "unico_config_slave_id": "int",
            "unico_config_timezone": "string",
            "unico_config_gps": "GPS | null",
            "unico_config_last_poll_time": "PlowUTCTime",
            "unico_config_poll_frequency": "int",
            "unico_config_retries": "int",
            "unico_config_comm_info": {
                "serial_port": "string",
                "comm_speed": "int",
                "timeout": "int",
            },
        },
        "response_type": "OnpingResponse ()",
        "response_schema": {},
    },
    "lufkin": {
        "driver": "lufkin",
        "endpoint": "POST /lufkin/location/add",
        "handler": "onping/Handler/Lufkin/Service.hs",
        "request_type": "NewLufkinLocationV2",
        "request_type_source": "OnPing.Frontend.Types.Lufkin",
        "request_schema": {
            "new_lufkin_location_v2_url": "string",
            "new_lufkin_location_v2_port": "int",
            "new_lufkin_location_v2_name": "string",
            "new_lufkin_location_v2_site_id": "int",
            "new_lufkin_location_v2_company_id": "int",
            "new_lufkin_location_v2_group_id": "int",
            "new_lufkin_location_v2_mobus_settings": {
                "rtu_or_tcp": "string",
                "ip": "string | null",
                "port": "int | null",
                "slave_id": "int | null",
                "baud_rate": "int | null",
            },
            "new_lufkin_location_v2_poll_frequency": "int",
            "new_lufkin_location_v2_last_poll_time": "PlowUTCTime",
            "new_lufkin_location_v2_retries": "int",
            "new_lufkin_location_v2_lwm_version": "string | null",
            "new_lufkin_location_v2_gps": "GPS | null",
        },
        "response_type": "OnpingResponse ()",
        "response_schema": {},
    },
    "osi-integration": {
        "driver": "osi-integration",
        "endpoint": "POST /osi/integration/location/add",
        "handler": "onping/Handler/Osi/Integration/Service.hs",
        "request_type": "OsiLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.OsiIntegration",
        "request_schema": {
            "osi_location_config_name": "string",
            "osi_location_config_site_id": "int",
            "osi_location_config_company_id": "int",
            "osi_location_config_group_id": "int",
            "osi_location_config_poll_frequency": "int",
            "osi_location_config_gps": "GPS | null",
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "hazard-pro": {
        "driver": "hazard-pro",
        "endpoint": "POST /hazard/pro/location/add",
        "handler": "onping/Handler/Hazard/Pro/Service.hs",
        "request_type": "HazardProLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.HazardPro",
        "request_schema": {
            "hazardProConfigLocId": "LocationId | null",
            "hazardProConfigRefId": "LocationIdRef | null",
            "hazardProConfigLocName": "string",
            "hazardProConfigUrl": "string",
            "hazardProConfigPort": "int",
            "hazardProConfigCompanyId": "int",
            "hazardProConfigSiteId": "int",
            "hazardProConfigGroupId": "int",
            "hazardProConfigPollFrequency": "int",
            "hazardProConfigLastPollTime": "PlowUTCTime",
            "hazardProConfigRetryCount": "int",
            "hazardProConfigGatewayUrl": "string",
            "hazardProConfigGatewayPort": "string",
            "hazardProConfigGatewayId": "int",
            "hazardProConfigCommTimeout": "int",
            "hazardProConfigGPS": "GPSStorable | null",
        },
        "response_type": "OnpingResponse ()",
        "response_schema": {},
    },
    "lumberjack-remote": {
        "driver": "lumberjack-remote",
        "endpoint": "POST /lumberjack/remote/add",
        "handler": "onping/Handler/LumberjackRemote/Service.hs",
        "request_type": "LumberjackRemoteLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.LumberjackRemote",
        "notes": "Outlier endpoint path: /lumberjack/remote/add (no /location/ segment).",
        "request_schema": {
            "remoteConfigLocId": "LocationId | null",
            "remoteConfigRefId": "LocationIdRef | null",
            "remoteConfigLocName": "string",
            "remoteConfigUrl": "string",
            "remoteConfigPort": "int",
            "remoteConfigCompanyId": "int",
            "remoteConfigSiteId": "int",
            "remoteConfigGroupId": "int",
            "remoteConfigLastPollTime": "int",
            "remoteConfigPollFrequency": "int",
            "remoteConfigRetryCount": "int",
            "remoteConfigParams": ["LumberjackRemoteParamConfig"],
            "remoteConfigGPS": "GPSStorable | null",
        },
        "response_type": "OnpingResponse LumberjackRemoteLocationConfig",
        "response_schema": "<echoes the request shape with populated remoteConfigLocId and remoteConfigRefId>",
    },
    "elynx": {
        "driver": "elynx",
        "endpoint": "POST /elynx/integration/location/add",
        "handler": "onping/Handler/ElynxIntegration/Service.hs",
        "request_type": "NewElynxLocation",
        "request_type_source": "OnPing.Frontend.Types.ElynxIntegration",
        "request_schema": {
            "newElynxLocationCompanyId": "int",
            "newElynxLocationSiteId": "int",
            "newElynxLocationName": "string",
            "newElynxLJSerial": "LJSerial",
            "newElynxLocationPollFrequency": "int",
            "newElynxLocationLastPollTime": "int",
            "newElynxLocationDeviceId": "ElynxGUID",
            "newElynxLocationGroupId": "int",
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "sitepro": {
        "driver": "sitepro",
        "endpoint": "POST /sitepro/location/add",
        "handler": "onping/Handler/Sitepro/Service.hs",
        "request_type": "SiteproLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.Sitepro",
        "request_schema": {
            "siteproLocationConfigName": "string",
            "siteproLocationConfigSiteId": "int",
            "siteproLocationConfigCompanyId": "int",
            "siteproLocationConfigGroupId": "int",
            "siteproLocationConfigPollFrequency": "int",
            "siteproLocationConfigLastPollTime": "int",
            "siteproLocationConfigGPS": "GPSStorable | null",
            "siteproLocationConfigLJSerial": "LJSerial",
            "siteproLocationConfigFacilitiesKeys": ["SiteproFacilityKey"],
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "tank-logix": {
        "driver": "tank-logix",
        "endpoint": "POST /tank-logix/location/add",
        "handler": "onping/Handler/TankLogix/Service.hs",
        "request_type": "TankLogixLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.TankLogix",
        "request_schema": {
            "tankLogixLocationConfigName": "string",
            "tankLogixLocationConfigSiteId": "int",
            "tankLogixLocationConfigCompanyId": "int",
            "tankLogixLocationConfigGroupId": "int",
            "tankLogixLocationConfigPollFrequency": "int",
            "tankLogixLocationConfigLastPollTime": "int",
            "tankLogixLocationConfigGPS": "GPSStorable | null",
            "tankLogixLocationConfigLJSerial": "LJSerial",
            "tankLogixLocationConfigSiteIDs": ["TankLogixSiteID"],
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "toku": {
        "driver": "toku",
        "endpoint": "POST /toku/location/add",
        "handler": "onping/Handler/Toku/Service.hs",
        "request_type": "TokuLocationConfig",
        "request_type_source": "OnPing.Frontend.Types.Toku",
        "request_schema": {
            "tokuLocationConfigSiteId": "int",
            "tokuLocationConfigName": "string",
            "tokuLocationConfigLJSerial": "LJSerial",
            "tokuLocationConfigCompanyId": "int",
            "tokuLocationConfigGroupId": "int",
            "tokuLocationConfigPollFrequency": "int",
            "tokuLocationConfigLastPollTime": "int",
            "tokuLocationConfigGPS": "GPSStorable | null",
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "dnp3": {
        "driver": "dnp3",
        "endpoint": "POST /dnp3/location/add",
        "handler": "onping/Handler/DNP3/Service.hs",
        "request_type": "DNP3LocationConfig",
        "request_type_source": "OnPing.Frontend.Types.DNP3",
        "request_schema": {
            "dnp3ConfigLocId": "LocationId | null",
            "dnp3ConfigRefId": "LocationIdRef | null",
            "dnp3ConfigLocName": "string",
            "dnp3ConfigServerUrl": "string",
            "dnp3ConfigServerPort": "int",
            "dnp3ConfigCompanyId": "int",
            "dnp3ConfigSiteId": "int",
            "dnp3ConfigGroupId": "int",
            "dnp3ConfigDeviceUrl": "string",
            "dnp3ConfigDevicePort": "int",
            "dnp3ConfigSource": "int",
            "dnp3ConfigDestination": "int",
            "dnp3ConfigGPS": "GPSStorable | null",
            "dnp3ConfigPollingRate": "int",
        },
        "response_type": "OnpingResponse LocationIdRef",
        "response_schema": {"_success": "int (LocationIdRef)"},
    },
    "sparkplug-bridge": {
        "driver": "sparkplug-bridge",
        "endpoint": "POST /sparkplug/bridge/add",
        "handler": "onping/Handler/SparkplugBridge/Service.hs",
        "request_type": "SparkplugBridgeConfiguration",
        "request_type_source": "OnPing.Frontend.Types.SparkplugBridge",
        "notes": "Outlier: adds a Sparkplug bridge, not a 'location'. Endpoint is /sparkplug/bridge/add.",
        "request_schema": {
            "sparkplugConfigPrimaryHost": "string",
            "sparkplugConfigSecondaryHost": "string",
            "sparkplugConfigSupportMQTT5": "bool",
            "sparkplugConfigNodeGroupId": "string",
            "sparkplugConfigNodeId": "string",
            "sparkplugConfigPrimaryHostAppId": "string | null",
            "sparkplugConfigGroupId": "int",
            "sparkplugConfigPort": "int",
            "sparkplugConfigLJSerial": "LJSerial",
            "sparkplugConfigTags": ["SparkplugTagConfig"],
        },
        "response_type": "OnpingResponse ()",
        "response_schema": {},
    },
}
